name: "Deploy to AWS"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: "Setup Node-js"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
        
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Install Dependencies"
        run: npm install

      - name: "Install PM2 Globally"
        run: npm install pm2 -Globally

      - name: "Run Tests"
        run: npm test

      - name: "Deploy Application"
        run: pm2 start src/index.js